apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-hello-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-hello-app
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
